#!/bin/bash

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    cat << 'EOF'
FlatInstall - Simple Flatpak Installer
Version 1.0

Usage: flatinstall
    Enter the name of app you want to install and it will do it for you!

Options:
  --help, -h    Show this help message and exit

Description:
  A simple Python-based Flatpak installer for Arch Linux.

Examples:
  flatinstall --help    # Show this help message
  flatinstall -h        # Show this help message
EOF
    exit 0
fi

exec python3 /usr/lib/flatinstall/main.py "$@"
